# Database Configuration
server:
  port: 8080

spring:
  application:
    name: MallApplication

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName:
  flyway:
    enabled: true
    locations: classpath:db/migration